- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
     - group_vars/all.yml
 
  tasks:

    - name: cloudformation operation
      cloudformation:
        stack_name: tier3Application
        state: "present"
        region: "{{ region }}"
        disable_rollback: true
        template: $workspace/template/cfn-template.yml
  
